// <auto-generated />
using CCImpactAgriculture_2024_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCImpactAgriculture_2024_Api.Migrations
{
    [DbContext(typeof(CCImpactAgricultureContext))]
    partial class CCImpactAgricultureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CCImpactAgriculture_2024_Api.Models.CCImpactAgricultureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adaptation_Strategies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Average_Temperature_C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CO2_Emissions_MT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Crop_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Crop_Yield_MT_per_HA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Economic_Impact_Million_USD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Extreme_Weather_Events")
                        .HasColumnType("int");

                    b.Property<decimal>("Fertilizer_Use_KG_per_HA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Irrigation_Access_Per")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pesticide_Use_KG_per_HA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Soil_Health_Index")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_Precipitation_mm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CCItem");
                });
#pragma warning restore 612, 618
        }
    }
}
